# To train the Object detection Model:

In [2]:
pip install ultralytics==8.0.0

Note: you may need to restart the kernel to use updated packages.


In [1]:
from ultralytics import YOLO

In [2]:
from ultralytics import YOLO

# # Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

# # Train the model with 2 GPUs
results = model.train(data='data.yaml', epochs=200, imgsz=640) 


100%|█████████████████████████████████████████████████████████████████████████████| 6.23M/6.23M [00:00<00:00, 8.87MB/s]



# Test Autmonatic Number Plate Object Detection Model:

In [1]:
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO(r'D:/Automatic-Number-Plate-Recognition--ANPR--main/ultralytics/runs/detect/train_model/weights/best.pt')

# Run inference on 'bus.jpg' with arguments
model.predict(r'D:/Automatic-Number-Plate-Recognition--ANPR--main/test.mp4', save=True, imgsz=320, conf=0.2)


Ultralytics YOLOv8.0.3  Python-3.11.5 torch-2.1.2+cpu CPU
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
video 1/1 (1/460) D:\Automatic-Number-Plate-Recognition--ANPR--main\test.mp4: 192x320 1 licence, 130.2ms
video 1/1 (2/460) D:\Automatic-Number-Plate-Recognition--ANPR--main\test.mp4: 192x320 1 licence, 125.0ms
video 1/1 (3/460) D:\Automatic-Number-Plate-Recognition--ANPR--main\test.mp4: 192x320 1 licence, 78.3ms
video 1/1 (4/460) D:\Automatic-Number-Plate-Recognition--ANPR--main\test.mp4: 192x320 141.7ms
video 1/1 (5/460) D:\Automatic-Number-Plate-Recognition--ANPR--main\test.mp4: 192x320 1 licence, 157.0ms
video 1/1 (6/460) D:\Automatic-Number-Plate-Recognition--ANPR--main\test.mp4: 192x320 109.4ms
video 1/1 (7/460) D:\Automatic-Number-Plate-Recognition--ANPR--main\test.mp4: 192x320 78.6ms
video 1/1 (8/460) D:\Automatic-Number-Plate-Recognition--ANPR--main\test.mp4: 192x320 1 licence, 140.8ms
video 1/1 (9/460) D:\Automatic-Number-Plate-Reco

[tensor([[4.74000e+02, 8.79000e+02, 6.07000e+02, 9.29000e+02, 6.84619e-01, 0.00000e+00]]),
 tensor([[4.85000e+02, 8.83000e+02, 6.11000e+02, 9.32000e+02, 6.66405e-01, 0.00000e+00]]),
 tensor([[4.72000e+02, 8.84000e+02, 6.37000e+02, 9.32000e+02, 3.66342e-01, 0.00000e+00]]),
 tensor([], size=(0, 6)),
 tensor([[4.89000e+02, 8.94000e+02, 6.14000e+02, 9.36000e+02, 2.51873e-01, 0.00000e+00]]),
 tensor([], size=(0, 6)),
 tensor([], size=(0, 6)),
 tensor([[4.79000e+02, 9.06000e+02, 6.09000e+02, 9.56000e+02, 2.97606e-01, 0.00000e+00]]),
 tensor([[4.75000e+02, 9.17000e+02, 6.07000e+02, 9.62000e+02, 3.38797e-01, 0.00000e+00]]),
 tensor([[4.60000e+02, 9.25000e+02, 6.07000e+02, 9.70000e+02, 2.79296e-01, 0.00000e+00]]),
 tensor([[4.67000e+02, 9.23000e+02, 5.97000e+02, 9.63000e+02, 4.75505e-01, 0.00000e+00]]),
 tensor([[4.56000e+02, 9.31000e+02, 6.05000e+02, 9.73000e+02, 6.57764e-01, 0.00000e+00]]),
 tensor([[4.46000e+02, 9.35000e+02, 5.95000e+02, 9.79000e+02, 5.05608e-01, 0.00000e+00]]),
 tensor([[4.

# License plate Recognize after Detecting  using easy-ocr

In [2]:
#!pip install easyocr

In [6]:
!python extract.py model='ultralytics/runs/detect/train_model/weights/best.pt' source='test.mp4' 

[2024-02-17 14:48:03,044][tensorflow][WARNING] - From C:\Users\smart\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.



Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
2024-02-17 14:47:53.688693: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Ultralytics YOLOv8.0.3  Python-3.11.5 torch-2.1.2+cpu CPU
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
video 1/1 (1/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 322.4ms
video 1/1 (2/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 315.4ms
video 1/1 (3/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 244.2ms
video 1/1 (4/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 311.8ms
video 1/1 (5/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 246.4ms
video 1/1 (6/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 164.2ms
video 1/1 (7/460) D:\ANPR 

In [4]:
!python extract.py model='D:/Automatic-Number-Plate-Recognition--ANPR--main/ultralytics/runs/detect/train_model/weights/best.pt' source='test.mp4' 

[2024-02-17 14:35:51,751][tensorflow][WARNING] - From C:\Users\smart\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.



Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
2024-02-17 14:35:42.874809: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Ultralytics YOLOv8.0.3  Python-3.11.5 torch-2.1.2+cpu CPU
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
video 1/1 (1/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 246.9ms
video 1/1 (2/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 252.9ms
video 1/1 (3/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 254.8ms
video 1/1 (4/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 264.3ms
video 1/1 (5/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 196.8ms
video 1/1 (6/460) D:\ANPR Webinar\test.mp4: 384x640 2 licences, 249.2ms
video 1/1 (7/460) D:\ANPR 

In [5]:
!python extract.py model='D:/Automatic-Number-Plate-Recognition--ANPR--main/ultralytics/runs/detect/train_model/weights/best.pt' source='test.jpg' 

[2024-02-17 14:47:42,895][tensorflow][WARNING] - From C:\Users\smart\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.



Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
2024-02-17 14:47:32.248733: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Ultralytics YOLOv8.0.3  Python-3.11.5 torch-2.1.2+cpu CPU
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
image 1/1 D:\ANPR Webinar\test.jpg: 416x640 1 licence, 238.1ms
Speed: 0.0ms pre-process, 238.1ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs\detect\train8
